---

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"


- name: restart docker service
  service: "name=docker state={{ docker_restart_handler_state }}"


- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"


- name: Install Docker Compose.
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

#- name: Upgrade pip
#  pip:
#    name: pip
#    state: forcereinstall

#- name: Upgrade python library - docker-compose
#  pip:
#    name:
#      - docker-compose


- name: Add docker user.
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  when: docker_users | length > 0

