    - name: sleep 10 seconds for node become ready 
      wait_for:
        timeout: 10
      delegate_to: localhost
    
    - name: Master get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      #when: "'master' in ansible_hostname"


    - name: "cluster Master Join token"
      debug:
        msg: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Master set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
      #when: "'master' in ansible_hostname"

    - name: COPY TOKEN FROM MASTER
      copy:
        content: "{{ join_command_raw.stdout_lines[0] }}"
        dest: kubeadm-connect-token.sh

    - name: COPY FROM REMOTE
      fetch: 
        src:  kubeadm-connect-token.sh
        dest: ./roles/k8s-installation/temp-files/
        remote_src: yes

